In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [2]:
np.random.seed(42)

df = pd.DataFrame({
    "Pclass": np.random.choice([1,2,3],100),
    "Sex": np.random.choice(["male","female"],100),
    "Age": np.random.randint(18,70,100).astype(float),
    "Fare": np.random.uniform(20,300,100),
    "Embarked": np.random.choice(["C","Q","S"],100),
    "Survived": np.random.choice([0,1],100)
})

df.loc[5,"Age"] = np.nan
df.loc[15,"Embarked"] = np.nan

df.head()

   Pclass     Sex   Age        Fare Embarked  Survived
0       3  female  45.0  204.795533        Q         1
1       1  female  42.0  248.822216        S         0
2       3  female  56.0  175.456227        C         1
3       3    male  50.0  168.302162        Q         0
4       1    male  18.0   87.718641        S         0

In [3]:
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

print("\nSummary")
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    100 non-null    int64
 1   Sex       100 non-null    object
 2   Age       99 non-null     float64
 3   Fare      100 non-null    float64
 4   Embarked  99 non-null     object
 5   Survived  100 non-null    int64
dtypes: float64(2), int64(2), object(2)
memory usage: 4.8+ KB
None

Missing Values
Pclass      0
Sex         0
Age         1
Fare        0
Embarked    1
Survived    0
dtype: int64

Summary
           Pclass        Age        Fare    Survived
count  100.000000  99.000000  100.000000  100.000000
mean     1.980000  43.151515  175.541660    0.470000
std      0.803779  15.709326   80.189228    0.501614
min      1.000000  18.000000   21.417243    0.000000
25%      1.000000  28.500000  110.518477    0.000000
50%      2.000000  45.000000  191.001080    0.000000
75%      3.000000  56.000000  244.297268    1.000000
max      3.000000  69.000000  297.215078    1.000000

In [4]:
X = df.drop("Survived", axis=1)
y = df["Survived"]

In [5]:
numeric_features = ["Age","Fare"]

categorical_features = [
    "Sex",
    "Embarked",
    "Pclass"
]

In [6]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [7]:
preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(80, 5)
(20, 5)

In [9]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

print("Training Data Shape:", X_train_processed.shape)

print("Testing Data Shape:", X_test_processed.shape)

Training Data Shape: (80, 10)
Testing Data Shape: (20, 10)

In [11]:
processed_train = pd.DataFrame(X_train_processed)

processed_train.head()

          0         1    2    3    4    5    6    7    8    9
0 -1.016560  1.304852  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
1  0.820143  1.212616  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0
2  1.580158  0.462524  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0
3 -0.256545 -0.550038  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0
4 -1.333234 -1.307787  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0

In [12]:
processed_train.to_csv(
    "Titanic_Preprocessed.csv",
    index=False
)

print("Preprocessed dataset exported successfully.")

Preprocessed dataset exported successfully.